import React from "react";
import {
    Document,
    Page,
    StyleSheet,
    View,
    Text,
} from "@react-pdf/renderer";
import { registerPdfFonts } from "@/features/pdf/fonts/registerPdfFonts";

registerPdfFonts();

const styles = StyleSheet.create({
    page: {
        paddingTop: 28,
        paddingBottom: 40, // footer 分を少し多めに取る
        paddingHorizontal: 32,
        fontSize: 10,
        lineHeight: 1.5,
        fontFamily: "NotoSansJP",
        position: "relative",
    },
    title: {
        fontSize: 18,
        marginBottom: 6,
        fontWeight: 700,
    },
    subTitle: {
        fontSize: 9,
        color: "#666666",
        marginBottom: 16,
    },
    content: {
        width: "100%",
    },
    footerLeft: {
        position: "absolute",
        left: 32,
        bottom: 16,
        fontSize: 9,
        color: "#666666",
    },
    footerRight: {
        position: "absolute",
        right: 32,
        bottom: 16,
        fontSize: 9,
        color: "#666666",
    },
});

export function PdfBaseDocument({
    title,
    subTitle,
    children,
}: {
    title: string;
    subTitle?: string;
    children: React.ReactNode;
}) {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <Text style={styles.title}>{title}</Text>
                {subTitle ? <Text style={styles.subTitle}>{subTitle}</Text> : null}

                <View style={styles.content}>{children}</View>

                <Text style={styles.footerLeft} fixed>
                    Generated by system
                </Text>

                <Text
                    style={styles.footerRight}
                    fixed
                    render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
                ></Text>
            </Page>
        </Document>
    );
}
